ttt.jl/.git:
	git submodule update --init ttt.jl/

# Submodules
skill/.git:
	git submodule update --init software/skill/
	make handicap -C software/skill/
glicko2/.git:
	git submodule update --init software/glicko2/
abrl/.git:
	git submodule update --init software/abrl/
	make -C software/abrl/ setup

