KGS.csv:
	wget https://github.com/mmazz/Analisis_go/releases/download/v1.0/KGS.tar.gz
	tar -xvf KGS.tar.gz

public-games.csv:
	wget https://downloads.gokgs.com/public-games.csv.gz
	gzip -d public-games.csv.gz
